// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Standalone NGINX egress gateway configuration (L7 backup).

use std::collections::BTreeMap;

use openshell_core::proto::{NetworkEndpoint, SandboxPolicy};
use crate::access::{endpoint_l7_allows, endpoint_l7_denies};
use crate::options::CompileOptions;
use crate::{CompileError, CompileResult};

#[derive(Debug, Clone)]
struct NginxVirtualHost {
    host: String,
    port: u16,
    allows: Vec<(String, String)>,
    denies: Vec<(String, String)>,
}

/// Compile a standalone NGINX config that enforces L7 rules derived from OpenShell policy.
///
/// Deploy NGINX as an egress reverse proxy. Point sandbox `HTTP(S)_PROXY` or cluster routing
/// so compromised direct egress is blocked by [`super::compile_network_policy`] while
/// legitimate traffic flows through this listener.
pub fn compile_nginx_conf(policy: &SandboxPolicy, opts: &CompileOptions) -> CompileResult<String> {
    opts.validate()?;
    let revision = opts.policy_revision.unwrap_or(0);
    let vhosts = collect_nginx_vhosts(policy)?;

    if vhosts.is_empty() {
        return Err(CompileError::NoL7Endpoints(
            "no REST or WebSocket endpoints with L7 rules in policy".into(),
        ));
    }

    let mut out = String::new();
    out.push_str(&format!(
        r#"# Generated by openshell-policy-egress — L7 backup only (not a replacement for OpenShell proxy).
# OpenShell revision: {revision}
# Listen: {listen_port}
# Binary-level rules are NOT represented here.

"#,
        revision = revision,
        listen_port = opts.nginx_listen_port,
    ));

    for vhost in &vhosts {
        out.push_str(&render_vhost(vhost, opts.nginx_listen_port));
        out.push('\n');
    }

    Ok(out)
}

fn collect_nginx_vhosts(policy: &SandboxPolicy) -> CompileResult<Vec<NginxVirtualHost>> {
    let mut by_host_port: BTreeMap<(String, u16), NginxVirtualHost> = BTreeMap::new();

    for rule in policy.network_policies.values() {
        for endpoint in &rule.endpoints {
            if !is_l7_endpoint(endpoint) {
                continue;
            }
            let host = endpoint.host.trim().to_lowercase();
            if host.is_empty() || host.contains('*') {
                return Err(CompileError::UnsupportedHostPattern(host));
            }
            let port = primary_port(endpoint);
            let key = (host.clone(), port);
            let entry = by_host_port.entry(key).or_insert(NginxVirtualHost {
                host,
                port,
                allows: Vec::new(),
                denies: Vec::new(),
            });

            for allow in endpoint_l7_allows(endpoint) {
                if allow.method == "WEBSOCKET_TEXT" {
                    continue;
                }
                entry.allows.push((allow.method, allow.path));
            }
            for deny in endpoint_l7_denies(endpoint) {
                entry.denies.push((deny.method, deny.path));
            }
        }
    }

    Ok(by_host_port.into_values().collect())
}

fn is_l7_endpoint(endpoint: &NetworkEndpoint) -> bool {
    matches!(
        endpoint.protocol.as_str(),
        "rest" | "websocket" | "graphql"
    ) && (!endpoint.access.is_empty() || !endpoint.rules.is_empty())
}

fn primary_port(endpoint: &NetworkEndpoint) -> u16 {
    if endpoint.port > 0 {
        return u16::try_from(endpoint.port).unwrap_or(443);
    }
    endpoint
        .ports
        .first()
        .and_then(|p| u16::try_from(*p).ok())
        .unwrap_or(443)
}

fn render_vhost(vhost: &NginxVirtualHost, listen_port: u16) -> String {
    let upstream = format!("upstream_{}", vhost.host.replace('.', "_"));
    let mut buf = format!(
        r#"upstream {upstream} {{
    server {host}:{port};
    keepalive 32;
}}

server {{
    listen {listen_port};
    server_name {host};

    # Default deny — OpenShell default-deny posture (backup layer).
    location / {{
        return 403 "openshell egress backup: denied";
    }}

"#,
        upstream = upstream,
        host = vhost.host,
        port = vhost.port,
        listen_port = listen_port,
    );

    for (method, path) in &vhost.denies {
        if let Some(loc) = render_deny_location(method, path) {
            buf.push_str(&loc);
        }
    }

    for (method, path) in &vhost.allows {
        if let Some(loc) = render_allow_location(&upstream, &vhost.host, method, path) {
            buf.push_str(&loc);
        }
    }

    buf.push_str("}\n");
    buf
}

fn render_allow_location(upstream: &str, host: &str, method: &str, path: &str) -> Option<String> {
    let (location_line, regex) = nginx_location(path)?;
    let method_check = render_method_check(method, true);

    Some(format!(
        r#"    {location_line} {{
        {method_check}
        proxy_pass https://{upstream};
        proxy_ssl_server_name on;
        proxy_set_header Host {host};
        proxy_http_version 1.1;
    }}

"#,
        location_line = if regex {
            format!("location ~ {location_line}")
        } else {
            format!("location {location_line}")
        },
        method_check = method_check,
        upstream = upstream,
        host = host,
    ))
}

fn render_deny_location(method: &str, path: &str) -> Option<String> {
    let (location_line, regex) = nginx_location(path)?;
    let method_check = render_method_check(method, false);

    Some(format!(
        r#"    {location_line} {{
        {method_check}
        return 403 "openshell egress backup: deny rule";
    }}

"#,
        location_line = if regex {
            format!("location ~ {location_line}")
        } else {
            format!("location {location_line}")
        },
        method_check = method_check,
    ))
}

fn render_method_check(method: &str, allow: bool) -> String {
    if method == "*" {
        return String::new();
    }
    let methods: Vec<&str> = method.split('|').collect();
    if allow {
        let allowed = methods
            .iter()
            .map(|m| format!("$request_method = {m}"))
            .collect::<Vec<_>>()
            .join(" | ");
        format!(
            r#"if (!({allowed})) {{ return 403 "openshell egress backup: method denied"; }}"#
        )
    } else {
        let denied = methods
            .iter()
            .map(|m| format!("$request_method = {m}"))
            .collect::<Vec<_>>()
            .join(" | ");
        format!(
            r#"if ({denied}) {{ return 403 "openshell egress backup: deny rule"; }}"#
        )
    }
}

/// Convert OpenShell path globs to NGINX location prefix or regex pattern.
fn nginx_location(path: &str) -> Option<(String, bool)> {
    if path.is_empty() || path == "**" || path == "/**" {
        return Some(("/".to_string(), false));
    }
    if path.contains('*') {
        let pattern = glob_to_nginx_regex(path);
        return Some((pattern, true));
    }
    Some((path.to_string(), false))
}

fn glob_to_nginx_regex(glob: &str) -> String {
    let mut out = String::from("^");
    let mut chars = glob.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '*' if chars.peek() == Some(&'*') => {
                chars.next();
                out.push_str(".*");
            }
            '*' => out.push_str("[^/]*"),
            '?' => out.push('.'),
            '.' | '+' | '(' | ')' | '|' | '^' | '$' | '@' | '%' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out.push('$');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use openshell_core::proto::{NetworkEndpoint, NetworkPolicyRule, SandboxPolicy};
    use regex::Regex;
    use crate::options::CompileOptions;

    #[test]
    fn nginx_conf_read_only_github() {
        let mut policy = SandboxPolicy {
            version: 1,
            ..Default::default()
        };
        policy.network_policies.insert(
            "github".into(),
            NetworkPolicyRule {
                endpoints: vec![NetworkEndpoint {
                    host: "api.github.com".into(),
                    port: 443,
                    protocol: "rest".into(),
                    access: "read-only".into(),
                    ..Default::default()
                }],
                ..Default::default()
            },
        );
        let conf = compile_nginx_conf(&policy, &CompileOptions::default()).unwrap();
        assert!(conf.contains("server_name api.github.com"));
        assert!(conf.contains("$request_method = GET"));
        assert!(conf.contains("return 403"));
    }

    #[test]
    fn glob_regex_conversion() {
        let re = Regex::new(&glob_to_nginx_regex("/repos/**")).unwrap();
        assert!(re.is_match("/repos/octocat/hello-world"));
    }
}
